import Tests.Basic
import Tests.Examples.Arith
import Tests.Examples.Balanced
import Tests.Examples.Csv
import Tests.Examples.Json
import Tests.Examples.SExp
import Tests.Examples.Lambda
import Tests.Examples.Lexer
import Tests.Byte
